export const PLACE_ORDER_REQUEST='PLACE_ORDER_REQUEST'
export const PLACE_ORDER_SUCCESS='PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_FAIL='PLACE_ORDER_FAIL'

export const ORDER_DETAILS_REQUEST='ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS='ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL='ORDER_DETAILS_FAIL'

export const ALL_ORDER_DETAILS_REQUEST='ALL_ORDER_DETAILS_REQUEST'
export const ALL_ORDER_DETAILS_SUCCESS='ALL_ORDER_DETAILS_SUCCESS'
export const ALL_ORDER_DETAILS_FAIL='ALL_ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST='ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS='ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL='ORDER_PAY_FAIL'
export const ORDER_PAY_RESET='ORDER_PAY_RESET'


export const ADMIN_ORDER_DETAILS_REQUEST='ADMIN_ORDER_DETAILS_REQUEST'
export const ADMIN_ORDER_DETAILS_SUCCESS='ADMIN_ORDER_DETAILS_SUCCESS'
export const ADMIN_ORDER_DETAILS_FAIL='ADMIN_ORDER_DETAILS_FAIL'


export const DELIVERED_ORDER_REQUEST='DELIVERED_ORDER_REQUEST'
export const DELIVERED_ORDER_SUCCESS='DELIVERED_ORDER_SUCCESS'
export const DELIVERED_ORDER_FAIL='DELIVERED_ORDER_FAIL'



