export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL'

export const DELETE_PRODUCT_REQUEST='DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL='DELETE_PRODUCT_FAIL'

export const CREATE_PRODUCT_REQUEST='CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS='CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL='CREATE_PRODUCT_FAIL'

export const UPDATE_PRODUCT_REQUEST='UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS='UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL='UPDATE_PRODUCT_FAIL'

export const FILTER_PRODUCT_REQUEST='FILTER_PRODUCT_REQUEST'
export const FILTER_PRODUCT_SUCCESS='FILTER_PRODUCT_SUCCESS'
export const FILTER_PRODUCT_FAIL='FILTER_PRODUCT_FAIL'

export const SEARCH_PRODUCT_SUCCESS='SEARCH_PRODUCT_SUCCESS'
export const SEARCH_PRODUCT_REQUEST='SEARCH_PRODUCT_REQUEST'
export const SEARCH_PRODUCT_FAIL='SEARCH_PRODUCT_FAIL'