export const REGISTER_USER_REQUEST='REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS='REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL='REGISTER_USER_FAIL'

export const LOGIN_USER_REQUEST='LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL'

export const FETCH_USER_DETAILS_REQUEST='FETCH_USER_DETAILS_REQUEST'
export const FETCH_USER_DETAILS_SUCCESS='FETCH_USER_DETAILS_SUCCESS'
export const FETCH_USER_DETAILS_FAIL='FETCH_USER_DETAILS_FAIL'

export const FETCH_USER_LIST_REQUEST='FETCH_USER_LIST_REQUEST'
export const FETCH_USER_LIST_SUCCESS='FETCH_USER_LIST_SUCCESS'
export const FETCH_USER_LIST_FAIL='FETCH_USER_LIST_FAIL'

export const DELETE_USER_REQUEST='DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL='DELETE_USER_FAIL'



export const GET_USER_DETAILS_REQUEST='GET_USER_DETAILS_REQUEST'
export const GET_USER_DETAILS_SUCCESS='GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAIL='GET_USER_DETAILS_FAIL'


export const UPDATE_USER_DETAILS_REQUEST='UPDATE_USER_DETAILS_REQUEST'
export const UPDATE_USER_DETAILS_SUCCESS='UPDATE_USER_DETAILS_SUCCESS'
export const UPDATE_USER_DETAILS_FAIL='UPDATE_USER_DETAILS_FAIL'
export const UPDATE_USER_DETAILS_RESET='UPDATE_USER_DETAILS_RESET'







